# ===========================================================================
# NEON Plant Diversity Explorer — ui.R
# ===========================================================================

# rarity-style tier badge for plots (richness-based) — reused look from the flagship
tier_badge <- function(label, color) tags$span(class = "tag-badge",
  style = sprintf("background:%s;border-color:%s;color:#fff", color, color), label)

ui <- bslib::page_fillable(
  theme = app_theme,
  window_title = "NEON Plant Diversity Explorer", fillable = FALSE,

  tags$head(
    tags$link(rel = "preconnect", href = "https://fonts.googleapis.com"),
    tags$link(rel = "preconnect", href = "https://fonts.gstatic.com", crossorigin = NA),
    tags$link(rel = "stylesheet",
      href = "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500..800&family=Rubik:wght@400;500;600;700;800&display=swap"),
    tags$link(rel = "stylesheet", href = "https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.min.css"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.all.min.js"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/html-to-image@1.11.11/dist/html-to-image.js"),
    tags$link(rel = "stylesheet", href = asset_url("styles.css")),
    tags$link(rel = "stylesheet", href = asset_url("plant.css")),
    tags$script(src = asset_url("app.js")),
    tags$script(src = asset_url("pincards.js"))
  ),
  useShinyjs(),

  # ---- persistent top control bar (theme + help) -------------------------
  # v2 flow: the sidebar is gone. The picker map IS the way to select a site
  # (its select panel lives on the landing/splash). The two controls that must
  # stay reachable everywhere — the theme toggle and the help dialog — sit in
  # this slim top-right bar above the hero. Same ids (help, colorMode) so the
  # server is untouched.
  div(class = "top-bar",
    div(class = "top-bar-brand",
      tags$span(class = "tb-mark", "\U0001F33F"),
      tags$span(class = "tb-title", "Plant Diversity Explorer")),
    div(class = "top-bar-actions",
      actionButton("help", tagList(bs_icon("question-circle"), " How it works"),
                   class = "btn-outline-dark btn-sm tb-help"),
      div(class = "tb-theme",
        tags$span(class = "tb-theme-lab", bs_icon("circle-half")),
        input_dark_mode(id = "colorMode", mode = "light")))
  ),

  # "Open a plot's profile" picker — was in the sidebar, now a hidden body block
  # revealed on site load (server: shinyjs::show("plotPickerWrap")). Same ids
  # (plotSel, surpriseBtn) so the server logic is untouched.
  hidden(div(id = "plotPickerWrap", class = "plot-picker-wrap",
    div(class = "ppw-row",
      div(class = "ppw-sel",
        selectizeInput("plotSel", label = tagList(bs_icon("search"), " Open a plot's profile"),
                       choices = NULL, width = "100%",
                       options = list(placeholder = "Pick a plot…"))),
      actionButton("surpriseBtn", tagList(bs_icon("dice-5-fill"), " Surprise me"),
                   class = "btn-outline-dark ppw-surprise")))),

  # ---- loading overlay ---------------------------------------------------
  div(id = "loadOverlay", class = "load-overlay",
    div(class = "load-card",
      div(class = "load-spin mascot-spin", MASCOT_CRITTER),
      div(class = "load-title", "Loading site data"),
      div(id = "loadSite", class = "load-site"),
      div(class = "load-bar"),
      div(class = "load-note", "Building the diversity profiles, cover maps, and charts."))),

  uiOutput("heroStats"),

  # ---- splash ------------------------------------------------------------
  div(id = "splash",
    div(class = "splash-guide",
      div(class = "sg-bubble", "Pick a site to start!"),
      div(class = "sg-mascot", MASCOT_CRITTER)),
    div(class = "splash",
      div(class = "app-hero app-hero-splash",
        h1(class = "app-title", "NEON Plant Diversity Explorer",
           span(class = "title-tag", "unofficial")),
        p(class = "app-subtitle",
          "A field guide to what grows where NEON samples: how rich each site is, what covers the ground, and where introduced plants are gaining a foothold. Built on the nested-quadrat plant survey (DP1.10058.001).")),
      p("Tap a ", tags$b("site"), " on the map (dot size is species richness) to explore it, or pick one by name in the panel below the map. You can also open the full ", tags$b("Browse all 46 sites"), " list."),
      div(class = "splash-colorby",
        radioButtons("splashColorBy", label = NULL, inline = TRUE,
          choices = c("Colour: invasion" = "invasion", "Colour: completeness" = "completeness"),
          selected = "invasion"),
        uiOutput("splashLegend")),
      mapPickerUI("picker", height = "520px", spinner = DDL$green),

      # ---- relocated select panel (was the sidebar) ----------------------
      # Same input ids the server's cascade + load path depend on (stateSel,
      # site, loadBtn). Tapping a dot is the primary path; this panel is the
      # by-name fallback. Same ids, so server.R is untouched. (This app loads
      # each site's full annual span from its bundle — no date window control.)
      div(class = "select-panel",
        div(class = "sp-head", bs_icon("sliders"),
            " Or pick a site by name"),
        div(class = "sp-row",
          div(class = "sp-field",
            selectInput("stateSel", label = tagList(bs_icon("geo-alt-fill"), " State"),
                        choices = NULL, width = "100%")),
          div(class = "sp-field",
            selectInput("site", label = tagList(bs_icon("pin-map-fill"), " Site"),
                        choices = NULL, width = "100%"))),
        uiOutput("siteBio"),
        actionButton("loadBtn", tagList(bs_icon("globe-americas"), " Explore this site"),
                     class = "btn-primary btn-lg load-btn sp-load", onclick = "smtLoadStart()")),

      # CLOSED-by-default site list (canonical "Browse all 46 sites" disclosure):
      # the splash stays clean; the full card grid is one tap away and scrolls.
      # WIDTH GOTCHA: this grid used to be always-visible and was what gave the
      # splash column intrinsic width (the width-less leaflet alone collapses to
      # 0). With the list collapsed there's no intrinsic-width content, so the
      # width floor now lives in CSS — `.splash { width:100% }` +
      # `.map-picker-wrap { min-width }` keep the picker map full-width when closed.
      tags$details(class = "site-browse",
        tags$summary(class = "site-browse-summary",
          tags$span(class = "sbs-label", bs_icon("list-ul"), " Browse all 46 sites"),
          tags$span(class = "sbs-chevron", bs_icon("chevron-down"))),
        div(class = "site-browse-body", uiOutput("siteCards"))))),

  # ---- main tabs ---------------------------------------------------------
  div(id = "mainTabsWrap", class = "main-tabs-wrap",
    navset_card_tab(id = "tabs",

      nav_panel(title = tagList(bs_icon("compass"), " Overview"), value = "overview",
        div(class = "home-nav",
          actionButton("goDiversity", tagList(bs_icon("diagram-3-fill"), div("Diversity"), tags$small("richness & species-area")), class = "home-btn"),
          actionButton("goInvasive", tagList(bs_icon("shield-exclamation"), div("Native vs Invasive"), tags$small("the invasion lens")), class = "home-btn home-btn-star"),
          actionButton("goExpected", tagList(bs_icon("clipboard-check"), div("Expected vs Observed"), tags$small("completeness & QC")), class = "home-btn"),
          actionButton("goLab", tagList(bs_icon("bullseye"), div("Diversity Lab"), tags$small("every plot, pinnable")), class = "home-btn"),
          actionButton("goPlot", tagList(bs_icon("flower1"), div("Plot Profile"), tags$small("drill into one plot")), class = "home-btn"),
          actionButton("goMap", tagList(bs_icon("map-fill"), div("Map"), tags$small("plots across the site")), class = "home-btn")),
        div(class = "tools-strip",
          actionButton("compareBtn", tagList(bs_icon("layout-split"), " Compare two sites"), class = "btn-outline-dark btn-sm"),
          downloadButton("allDataZip", "Download all data (CSV)", class = "btn-outline-dark btn-sm")),
        card(full_screen = TRUE,
          card_head("bar-chart-steps", "What covers the ground: most abundant plants",
            info_pop("Cover composition",
              p("Mean ", tags$b("percent cover"), " per species, from the 1 m² quadrats, summed across the site. Bars are coloured ", tags$span(style="color:#1a7f37;font-weight:700","native"), " vs ", tags$span(style="color:#c1502e;font-weight:700","introduced"), "."),
              p("Cover is an ocular estimate and vegetation layers overlap, so site-summed cover is a relative measure, not a percentage of ground."))),
          uiOutput("overviewInsight"),
          spin(plotlyOutput("coverBar", height = "440px"))),
        card(card_head("stars", "The story so far",
            info_pop("Story", p("Written from this site's live data, the same numbers the rest of the app uses."))),
          uiOutput("siteInsights")),
        h4(class = "section-title", bs_icon("flower2"), " Ground cover here"),
        spin(plotlyOutput("groundBar", height = "260px"))),

      nav_panel(title = tagList(bs_icon("diagram-3-fill"), " Diversity"), value = "diversity",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("How diverse is this site?",
             info_pop("What richness is, and isn't",
               p("Richness counts ", tags$b("how many species"), " are present. It is composition, ", tags$b("not"), " productivity or ecosystem health."),
               p("In drylands the two can pull apart: a richness uptick is often introduced annual/forb addition after disturbance, meaning ", tags$b("more taxa, less native function"), ". More species ≠ more biomass or a healthier system."),
               p("For a standing-stock (productivity) signal, veg-structure basal area is the honest measure; this tab's richness reads composition."))),
          p("Richness across NEON's nested quadrat scales, the diversity profile, and a bias-corrected estimate of how many species are really out there."))),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE,
            card_head("graph-up", "Species–area curve (nested quadrats)",
              info_pop("Species-area",
                p("Mean species richness as sampled area grows from a 1 m² subplot → 10 m² → 100 m² corner → the 400 m² plot. NEON's nested design measures this directly."),
                p("A curve still climbing steeply at 400 m² means the site is ", tags$b("undersampled"), ". There's more out there than the plots have caught."))),
            uiOutput("saInsight"),
            spin(plotlyOutput("saPlot", height = "360px"))),
          card(full_screen = TRUE,
            card_head("diagram-2", "Diversity profile (Hill numbers)",
              info_pop("Hill numbers",
                p("Three views in one unit, an ", tags$b("effective number of species"), " weighted by ", tags$em("q"), " (how much rare species count): q0 = richness, q1 = exp(Shannon) (common species), q2 = inverse Simpson (dominant species)."),
                p("When q1/q2 sit far below q0, a few species ", tags$b("dominate"), " the cover."))),
            uiOutput("hillInsight"),
            spin(plotlyOutput("hillPlot", height = "260px")))),
        card(card_head("calculator", "How many species are really here? (Chao2)",
            info_pop("Chao2",
              p(tags$b("Chao2"), " is an incidence-based, bias-corrected ", tags$b("minimum"), " estimate of total richness, a floor that includes species the plots haven't caught yet, from how many species were seen in exactly one vs two subplots (Chao 1987)."),
              p("Incidence (presence across subplots), not cover, is the right input here. When species-seen-in-exactly-two are scarce it's unstable and flagged a lower bound."))),
          uiOutput("chaoBanner"))),

      nav_panel(title = tagList(bs_icon("shield-exclamation"), " Native vs Invasive"), value = "invasive",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Where are introduced plants gaining ground?"),
          p("The plant-monitoring signal land managers act on: how much of the cover is introduced, which species, and (using the nested design) where invasion is getting a foothold at the finest scale."))),
        card(full_screen = TRUE,
          card_head("graph-up-arrow", "Introduced cover share, over time",
            info_pop("Invaded cover",
              p("The share of total vegetative cover contributed by ", tags$span(style="color:#c1502e;font-weight:700","introduced"), " species, by year."),
              p("Status is NEON's ", tags$code("nativeStatusCode"), "; the % of species with ", tags$b("unknown"), " status is shown so you can judge how complete the picture is."))),
          uiOutput("invInsight"),
          spin(plotlyOutput("invTrend", height = "320px"))),
        layout_columns(col_widths = c(6, 6),
          card(full_screen = TRUE,
            card_head("exclamation-triangle-fill", "Invasive watchlist",
              info_pop("Watchlist", p("Introduced species ranked by mean 1 m² cover and how many plots they reach. The widespread, high-cover ones are the management priority."))),
            spin(DT::DTOutput("invTable"))),
          card(full_screen = TRUE,
            card_head("zoom-in", "Invasion-pressure index: the foothold detector",
              info_pop("Invasion pressure",
                p("A NEONize original. Because richness is measured at every nested scale, we can ask: how many introduced species are already detectable at the ", tags$b("smallest (1 m²)"), " scale, where they're cheap to catch but scary to a manager?"),
                p("Each dot is a plot: introduced species found at 1 m² (x) vs across the whole 400 m² plot (y). Plots high on x have invaders established right down to the finest grain."),
                p(tags$b("Reading a dot."), " Each dot is one introduced species. Left to right is how many plots it turns up in when you look at just the small 1 m2 quadrats; bottom to top is how many plots it turns up in across the whole 400 m2 plot. A species sitting right on the diagonal 1:1 line is found at the same breadth either way, so it only shows up where you can already see it up close. A species sitting well above the line is turning up across the broader plot far more often than its 1 m2 footholds alone would suggest. That gap above the line is the signature of an invader that has spread past a chance toehold and gained a real foothold, the kind worth watching before it fills in."))),
            spin(plotlyOutput("pressurePlot", height = "360px")))) ),

      nav_panel(title = tagList(bs_icon("clipboard-check"), " Expected vs Observed"), value = "expected",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("What should grow here, and what did NEON find?",
            info_pop("Expected vs Observed",
              p(tags$b("Expected"), " = the plants the NRCS Ecological Site lists for this kind of soil and climate (its reference plant community), resolved from the site's coordinates."),
              p("NEON samples a small plot area (~400 m² per plot) at peak greenness, so a species ", tags$b("expected but not found"), " usually means it just wasn't in the sampled patch, ", tags$b("not"), " that anything is wrong."),
              p("The ", tags$b("review"), " list is where a second look pays off: a plant NEON recorded that the reference community doesn't list (a new invader, a range edge, or a possible mis-ID)."))),
          p(HTML("<b>Expected</b> = the plants NRCS says this soil &amp; climate can support (its ecological site reference community). The one lane worth a second look is <b>observed-but-unexpected</b>; the rest is confirmation and completeness.")))),

        uiOutput("evoHeader"),
        uiOutput("evoHeadline"),
        uiOutput("evoCoarse"),

        # A — confirmation (green)
        card(full_screen = TRUE, class = "evo-bucket evo-card evo-a",
          card_head("check2-circle", "Reference flora detected here",
            info_pop("Bucket A · expected & observed",
              p("Species the NEON crews recorded that are also on the NRCS reference list for this ecological site, the overlap that confirms the site is what the soil survey says it is."),
              p("Sorted by the reference community's expected production (the species you'd most expect to dominate float to the top)."))),
          div(class = "evo-dl-row",
            downloadButton("evoCsvA", "Download (CSV + codebook ZIP)", class = "smt-clear-btn")),
          div(class = "evo-tbl-wrap", DT::DTOutput("evoTableA", width = "100%"))),

        # C — the review lane (clay)
        card(full_screen = TRUE, class = "evo-bucket evo-card evo-c",
          card_head("search", "Observed here, not in the reference list, worth a look",
            info_pop("Bucket C · observed, not expected",
              p("Plants NEON recorded that the NRCS reference community for this ecological site does not list. Two very different stories live here:"),
              tags$ul(
                tags$li(HTML("<b>Introduced</b>, an invasion signal; ties to the Native-vs-Invasive lens.")),
                tags$li(HTML("<b>Native, not recorded for this state</b>, a range edge, a finer ID than the soil survey used, or (rarely) a mis-ID."))),
              p("This is a ", tags$b("state-level plausibility check, not an error detector"), ". The reference list is one soil unit's associate list, far narrower than the whole state flora. So a native that ", tags$b("is"), " on the state flora, just not this soil unit, is set aside as a regional associate (we don't treat it as a problem); we keep here the introduced species and the natives that aren't even recorded for this state, the ones actually worth a look."),
              p("Labelled “review”, never “error”. Gaps in the reference list are real and common."))),
          div(class = "evo-subhead", bs_icon("info-circle"),
            HTML("A <b>state-level plausibility check</b>, and a <b>completeness</b> instrument, not an error detector. These turned up here but aren't on this site's single soil-unit reference list. We keep the ones that aren't even recorded for this state (worth a look) and set aside the ones that are on the state flora, just not this soil unit.")),
          uiOutput("evoRegionalNote"),
          div(class = "evo-dl-row",
            downloadButton("evoCsvC", "Download (CSV + codebook ZIP)", class = "smt-clear-btn")),
          div(class = "evo-tbl-wrap", DT::DTOutput("evoTableC", width = "100%"))),

        # B — completeness (neutral, never red)
        card(full_screen = TRUE, class = "evo-bucket evo-card evo-b",
          card_head("clipboard-data", "Expected but not detected: a completeness view",
            info_pop("Bucket B · expected but absent",
              p("Reference species NEON did ", tags$b("not"), " detect in its plots. This is overwhelmingly ", tags$b("non-detection"), ": NEON samples ~400 m² per plot, while an ecological site lists the whole site's potential vegetation under reference conditions."),
              p("It can also be a legitimate ", tags$b("state transition"), " (e.g. a shrub-encroached desert grassland). Read it as completeness or as an ecological pattern, ", tags$b("never as missing data or error.")),
              p("Sorted by expected production; the ", tags$b("reference dominants"), " not detected are shown in bold, the most informative gaps."))),
          div(class = "evo-subhead", bs_icon("info-circle"),
            "Not a problem list. NEON samples ~400 m² per plot, so these are mostly species just outside the sampled patch."),
          div(class = "evo-dl-row",
            downloadButton("evoCsvB", "Download (CSV + codebook ZIP)", class = "smt-clear-btn")),
          div(class = "evo-tbl-wrap", DT::DTOutput("evoTableB", width = "100%"))),

        # data-quality cross-checks (the true-QC lane) — needs only occ, so it stays
        # visible even when no reference list is bundled for the site
        card(class = "evo-card",
          card_head("clipboard-pulse", "Data-quality cross-checks",
            info_pop("True QC",
              p("Two genuine data-quality signals, kept separate from the completeness view above (these don't need a reference list):"),
              tags$ul(
                tags$li(HTML("<b>Nativity disagreement</b>, NEON's native/introduced label differs from USDA PLANTS for the same species.")),
                tags$li(HTML("<b>Implausible cover</b>, total cover in one 1 m² quadrat far exceeding what overlapping canopy layers explain (an entry-error backstop)."))))),
          div(class = "evo-dl-row",
            downloadButton("evoReport", tagList(bs_icon("download"), " Full report (CSV + codebook ZIP)"), class = "smt-snap-btn")),
          uiOutput("evoFlags"))),

      nav_panel(title = tagList(bs_icon("cloud-sun"), " Environment"), value = "environment",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Does the vegetation track the climate?"),
          p("Each survey year's plant signal against that year's climate and phenology, from co-located NEON sensors at this site. Plant surveys are annual and these records are short, so read this as ", tags$b("exploratory"), ". The permutation test says how easily chance alone could explain the link."))),
        div(class = "env-pop-bar",
          div(class = "env-pop-row",
            div(class = "env-pop-sel",
              selectInput("envMetric", tagList(bs_icon("flower1"), " Plant signal"),
                          choices = c("Species richness (diversity)" = "richness",
                                      "% introduced cover" = "pct_introduced",
                                      "Total cover" = "total_cover"),
                          selected = "richness", width = "100%")),
            div(class = "env-pop-sel",
              selectInput("envLayer", tagList(bs_icon("cloud-sun"), " Climate / phenology driver"),
                          choices = c("Strongest driver" = "best"), selected = "best", width = "100%")))),
        uiOutput("envSourceNote"),
        uiOutput("envCorrNote"),
        uiOutput("envCaveat"),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE,
            card_head("graph-up", "Plant signal vs the driver, by survey year",
              info_pop("Reading this",
                p("Each point is one survey year: the plant signal (y) against that year's driver value (x), at the lag with the strongest rank-correlation."),
                p("A dashed fit line is drawn ", tags$b("only when the permutation test clears chance"), " (p < 0.05); otherwise the points stand alone. On this few points the ", tags$b("shape"), " matters more than the exact r."))),
            spin(plotlyOutput("envScatter", height = "360px"))),
          card(full_screen = TRUE,
            card_head("bar-chart-steps", "Which driver does it track best?",
              info_pop("Driver ranking",
                p("Spearman |r| for each driver at its best lag (0–2 yr). These bars ARE the search the permutation test corrects for; they are ", tags$b("not independent evidence"), ", and on a short record none may be distinguishable from chance."))),
            spin(plotlyOutput("envDriverRank", height = "360px")))),
        uiOutput("seasonalDriver"),
        card(card_head("calendar3", "The two series over time",
            info_pop("Context", p("The plant signal (left axis) and the selected driver (right axis) across the years, the raw movement behind the correlation."))),
          spin(plotlyOutput("envTrend", height = "300px"))),
        div(class = "env-export-row",
          tags$span(class = "env-export-lab", bs_icon("download"), " Take the numbers with you:"),
          downloadButton("envSeriesCsv", "Matched series (CSV)", class = "smt-clear-btn"),
          downloadButton("envRankCsv", "Driver rank + permutation p (CSV)", class = "smt-clear-btn"))),

      # ---- Search the network -------------------------------------------------
      # Queries a small precomputed index (data/search_index.rds) loaded once at
      # boot — no live fetch, instant. Two modes: find a species across sites, or
      # filter sites by introduced-cover threshold. Both jump to a site's Overview.
      nav_panel(title = tagList(bs_icon("search"), " Search"), value = "search",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Search the network"),
          p("Look across every bundled NEON site at once. Find which sites a plant turns up at, or pull the sites by how invaded they are. This reads a small index built into the app, so it answers instantly without fetching anything."))),
        div(class = "search-modebar",
          radioButtons("searchMode", NULL, inline = TRUE,
                       choices = c("Find a species" = "taxon",
                                   "Filter sites by cover" = "threshold"),
                       selected = "taxon")),

        conditionalPanel("input.searchMode == 'taxon'",
          layout_columns(col_widths = c(5, 7),
            card(card_head("flower2", "Pick a species"),
              p(class = "dim", style = "margin:0 0 10px",
                "Start typing a scientific name. The list holds every species recorded at any bundled site."),
              selectizeInput("searchTaxon", NULL, choices = NULL, width = "100%",
                             options = list(placeholder = "e.g. Eragrostis lehmanniana",
                                            maxOptions = 1000)),
              uiOutput("searchTaxonMeta")),
            card(full_screen = TRUE,
              card_head("geo-alt", "Where it occurs",
                info_pop("Reading this",
                  p("One row per site where this species was recorded, with the site's mean 1 m^2 percent cover for it and the years it was seen. Cover is a ", tags$b("within-site index"), ", not an absolute ranking across sites."))),
              uiOutput("searchTaxonCount"),
              div(style = "width:100%", DTOutput("searchTaxonTbl"))))),

        conditionalPanel("input.searchMode == 'threshold'",
          layout_columns(col_widths = c(5, 7),
            card(card_head("sliders", "Set the filter"),
              radioButtons("threshNativity", "Cover of",
                           choices = c("Introduced" = "Introduced", "Native" = "Native"),
                           selected = "Introduced", inline = TRUE),
              div(class = "thresh-row",
                selectInput("threshDir", "is", width = "120px",
                            choices = c("at least" = "ge", "at most" = "le"), selected = "ge"),
                numericInput("threshPct", "% of site cover", value = 10, min = 0, max = 100, step = 5, width = "150px")),
              tags$hr(),
              p(class = "dim", style = "margin:0 0 8px", "Or jump straight to a known invader:"),
              selectizeInput("threshInvader", "Find an introduced species", choices = NULL, width = "100%",
                             options = list(placeholder = "e.g. Bromus tectorum", maxOptions = 1000))),
            card(full_screen = TRUE,
              card_head("list-ul", "Matching sites",
                info_pop("Reading this",
                  p("Sites are ranked by the chosen cover share. These shares are ", tags$b("within-site indices"), " built the same way as each site's hero number, so a high % means a site that is heavily invaded relative to its own cover, not the most invaded acre in the network."))),
              uiOutput("searchThreshCount"),
              div(style = "width:100%", DTOutput("searchThreshTbl"))))),

        p(class = "dim", style = "margin-top:14px;font-size:12px",
          "Percent cover is a relative within-site index from the 1 m^2 quadrats (space-for-time, not an absolute or census number). Pick a site and press Explore to load it into every other tab.")),

      nav_panel(title = tagList(bs_icon("bullseye"), " Diversity Lab"), value = "lab",
        div(class = "tab-head",
          div(class = "tab-head-text",
            h4("Every plot on one map",
               info_pop("Diversity Lab",
                 p("Each dot is a ", tags$b("plot"), ", placed by its ", tags$b("species richness"), " (x) and the ", tags$b("share of its cover that's introduced"), " (y). Median crosshairs split it into four corners."),
                 p(tags$b("Tap a dot"), " to pin its card; drag it, resize it, and ", tags$b("download the chart with the cards on it"), ". Tap “Open plot profile” for the full drill-down."))),
            p("Each dot is a plot: richness × how invaded it is. Tap to pin a card; open any plot's full profile.")),
          div(class = "sizelab-controls",
            selectInput("labColor", tagList(bs_icon("palette"), " Colour by"),
                        choices = c("Habitat (NLCD)" = "nlcdClass", "Plot type" = "plotType",
                                    "Dominant family" = "domfam"), selected = "nlcdClass", width = "220px"))),
        card(full_screen = TRUE,
          card_head("bullseye", "Richness × introduced-cover, by plot",
            info_pop("Reading this",
              p("Left = fewer species; right = more species; top = more introduced cover; bottom = native-dominated cover. The ", tags$span(style="color:#c9a300;font-weight:700","gold diamond"), " is the plot you're viewing."),
              p("More species (right) is ", tags$b("not"), " automatically better: richness is composition, not health. In drylands a richness uptick can be introduced-forb addition, so read the y-axis (native vs introduced cover), not just the count."),
              p(tags$b("What a pattern means."), " Each dot is one plot. Left to right is how many plant species the crew found in that plot; bottom to top is how much of the plot's cover is introduced rather than native. If the cloud of dots tilts downward as you move right (a negative slope), the most species-rich plots tend to be the least invaded, which is the picture you'd expect if introduced plants are crowding native species out: more introduced cover, fewer natives left. If the cloud is flat (no tilt), richness and invasion just aren't tracking each other here; a plot can be species-rich or species-poor at any level of invasion. If it tilts upward (a positive slope), the more-invaded plots also hold more species, which usually points to disturbance: digging, grazing, or a road edge lets newcomers in while the natives are still hanging on, so the two simply pile up together."),
              p(tags$b("The honest caveats."), " This is a relationship you can see, not a cause you can prove. A downward tilt is consistent with invasion pushing natives out, but it can also come from both responding to the same thing (poorer soil, more disturbance), so read it as a lead to follow, not a verdict. And remember what each axis really is: the x-axis is a count of species at the 400 m2 plot scale, while the y-axis is a relative cover index from overlapping ocular estimates in the 1 m2 quadrats, not a share of bare ground. A plot at 30% introduced cover has not lost 30% of its ground to weeds; it means introduced plants make up about 30% of the leafy cover the crew estimated."))),
          div(class = "sizelab-toolbar",
            tags$button(class = "smt-snap-btn", type = "button", onclick = "smtSaveScatter()",
                        bsicons::bs_icon("camera-fill"), " Download (with pinned cards)"),
            tags$button(class = "smt-clear-btn", type = "button", onclick = "smtClearPins()",
                        bsicons::bs_icon("eraser-fill"), " Clear pins"),
            tags$span(class = "sizelab-hint", bs_icon("hand-index-thumb"), " interactive · tap a dot to pin its card")),
          div(class = "smt-pinnable", spin(plotlyOutput("labScatter", height = "540px")))),
        uiOutput("plotCardSlot")),

      nav_panel(title = tagList(bs_icon("flower1"), " Plot Profile"), value = "plot",
        uiOutput("plotProfile")),

      nav_panel(title = tagList(bs_icon("map-fill"), " Map"), value = "map",
        div(class = "tab-head",
          div(class = "tab-head-text",
            h4("Plots across the site"),
            p("Each marker is a NEON plot, sized by richness and coloured by how invaded it is. The selected plot glows gold.")),
          div(class = "map-controls",
            selectInput("mapMetric", "Colour by", width = "180px",
                        choices = c("% introduced cover" = "pct_introduced", "Species richness" = "richness")),
            selectInput("view", "Basemap", width = "160px",
                        choices = c("Satellite" = "Esri.WorldImagery", "Terrain" = "Esri.WorldTopoMap",
                                    "Light" = "CartoDB.Positron")))),
        spin(leafletOutput("map", height = "620px"))),

      nav_panel(title = tagList(bs_icon("info-circle"), " About"), value = "about",
        uiOutput("aboutPanel"))
    )),

  div(class = "ddl-footer",
    div(tags$a(class = "custom-cta",
      href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Plant%20Diversity%20Explorer",
      span(class = "hand", "\U0001F44B"), "Questions or feedback? Get in touch with Desert Data Labs.")),
    p(style = "margin-top:12px",
      HTML("Built by <strong>Desert Data Labs</strong> · Tucson, AZ · get in touch →"),
      tags$a(href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Plant%20Diversity%20Explorer", "desertdatalabs@gmail.com")),
    p(style = "font-size:12px;opacity:.85",
      "Data: NEON Plant Presence & Percent Cover (DP1.10058.001). Not affiliated with NEON, Battelle, or the NSF. An educational data-exploration tool."))
)
