# ===========================================================================
# NEON Plant Diversity Explorer — ui.R
# ===========================================================================

# rarity-style tier badge for plots (richness-based) — reused look from the flagship
tier_badge <- function(label, color) tags$span(class = "tag-badge",
  style = sprintf("background:%s;border-color:%s;color:#fff", color, color), label)

ui <- bslib::page_fillable(
  theme = app_theme,
  window_title = "NEON Plant Diversity Explorer", fillable = FALSE,

  tags$head(
    tags$meta(name = "description", content = "Explore nested-quadrat plant diversity, composition, introduced cover, and data quality across 46 bundled NEON terrestrial sites."),
    tags$link(rel = "stylesheet", href = asset_url("vendor/sweetalert2-11.10.0.min.css")),
    tags$script(src = asset_url("vendor/sweetalert2-11.10.0.all.min.js")),
    tags$script(src = asset_url("vendor/html-to-image-1.11.11.js")),
    tags$link(rel = "stylesheet", href = asset_url("styles.css")),
    tags$link(rel = "stylesheet", href = asset_url("plant.css")),
    tags$script(src = asset_url("app.js")),
    tags$script(src = asset_url("pincards.js"))
  ),
  useShinyjs(),
  tags$a(class = "skip-link", href = "#main-content", "Skip to the explorer"),

  # ---- persistent top control bar (theme + help) -------------------------
  # v2 flow: the sidebar is gone. The picker map IS the way to select a site
  # (its select panel lives on the landing/splash). The two controls that must
  # stay reachable everywhere — the theme toggle and the help dialog — sit in
  # this slim top-right bar above the hero. Same ids (help, colorMode) so the
  # server is untouched.
  div(class = "top-bar",
    div(class = "top-bar-brand",
      tags$span(class = "tb-mark", "\U0001F33F"),
      div(tags$span(class = "tb-title", "Plant Diversity Explorer"),
          tags$span(class = "tb-role", "composition & invasion context"))),
    div(class = "top-bar-actions",
      tags$span(id = "appStatus", class = "app-status", role = "status", `aria-live` = "polite",
                `data-app-ready` = "false", "Connecting…"),
      tags$a(class = "suite-link", href = "https://tgilbert14.github.io/NEON-Driver-Cascade/",
             target = "_blank", rel = "noopener", "NEON suite"),
      actionButton("help", tagList(bs_icon("question-circle"), " How it works"),
                   class = "btn-outline-dark btn-sm tb-help"),
      div(class = "tb-theme",
        tags$span(class = "tb-theme-lab", bs_icon("circle-half")),
        input_dark_mode(id = "colorMode", mode = "light")))
  ),

  # "Open a plot's profile" picker — was in the sidebar, now a hidden body block
  # revealed on site load (server: shinyjs::show("plotPickerWrap")). Same ids
  # (plotSel, surpriseBtn) so the server logic is untouched.
  hidden(div(id = "plotPickerWrap", class = "plot-picker-wrap",
    div(class = "ppw-row",
      div(class = "ppw-sel",
        selectizeInput("plotSel", label = tagList(bs_icon("search"), " Open a plot's profile"),
                       choices = NULL, width = "100%",
                       options = list(placeholder = "Pick a plot…"))),
      actionButton("surpriseBtn", tagList(bs_icon("dice-5-fill"), " Surprise me"),
                   class = "btn-outline-dark ppw-surprise")))),

  # ---- loading overlay ---------------------------------------------------
  div(id = "loadOverlay", class = "load-overlay", role = "status", `aria-live` = "polite",
      `aria-busy` = "true", `aria-atomic` = "true",
    div(class = "load-card",
      div(class = "load-spin mascot-spin", MASCOT_CRITTER),
      div(class = "load-title", "Loading site data"),
      div(id = "loadSite", class = "load-site"),
      div(class = "load-bar", `aria-hidden` = "true"),
      div(class = "load-note", "Building the diversity profiles, cover maps, and charts."),
      tags$button(id = "loadRecovery", class = "load-recovery", type = "button",
                  onclick = "window.location.reload()", "Reload the explorer"))),

  tags$main(id = "main-content", tabindex = "-1",
    uiOutput("heroStats"),

  # ---- splash ------------------------------------------------------------
  div(id = "splash",
    div(class = "splash-guide",
      div(class = "sg-bubble", "Pick a site to start!"),
      div(class = "sg-mascot", MASCOT_CRITTER)),
    div(class = "splash",
      div(class = "app-hero app-hero-splash",
        div(class = "app-role-chip", "COMPOSITION & INVASION CONTEXT"),
        h1(class = "app-title", "NEON Plant Diversity Explorer",
           span(class = "title-tag", "unofficial")),
        p(class = "app-subtitle",
          "See how plant communities change from 1 to 400 m²—and where introduced cover warrants a closer look. Built from NEON's nested-quadrat survey (DP1.10058.001), with effort and uncertainty kept visible.")),
      div(class = "splash-contract",
        tags$span(bs_icon("grid-3x3-gap"), " 46 bundled sites"),
        tags$span(bs_icon("rulers"), " 1 → 400 m² grain"),
        tags$span(bs_icon("shield-check"), " context, not productivity")),
      p("Choose a ", tags$b("site"), " on the map to begin. Dot size shows the number of sampled plots—not raw richness—so the map does not turn unequal effort into a biodiversity ranking. You can also use the by-name picker or browse all 46 sites."),
      div(class = "splash-colorby",
        radioButtons("splashColorBy", label = NULL, inline = TRUE,
          choices = c("Colour: invasion" = "invasion", "Colour: completeness" = "completeness"),
          selected = "invasion"),
        uiOutput("splashLegend")),
      mapPickerUI("picker", height = "520px", spinner = DDL$green),

      # ---- relocated select panel (was the sidebar) ----------------------
      # Same input ids the server's cascade + load path depend on (stateSel,
      # site, loadBtn). Tapping a dot is the primary path; this panel is the
      # by-name fallback. Same ids, so server.R is untouched. (This app loads
      # each site's full annual span from its bundle — no date window control.)
      div(class = "select-panel",
        div(class = "sp-head", bs_icon("sliders"),
            " Or pick a site by name"),
        div(class = "sp-row",
          div(class = "sp-field",
            selectInput("stateSel", label = tagList(bs_icon("geo-alt-fill"), " State"),
                        choices = NULL, width = "100%")),
          div(class = "sp-field",
            selectInput("site", label = tagList(bs_icon("pin-map-fill"), " Site"),
                        choices = NULL, width = "100%"))),
        uiOutput("siteBio"),
        actionButton("loadBtn", tagList(bs_icon("globe-americas"), " Explore this site"),
                     class = "btn-primary btn-lg load-btn sp-load", onclick = "smtLoadStart()")),

      # CLOSED-by-default site list (canonical "Browse all 46 sites" disclosure):
      # the splash stays clean; the full card grid is one tap away and scrolls.
      # WIDTH GOTCHA: this grid used to be always-visible and was what gave the
      # splash column intrinsic width (the width-less leaflet alone collapses to
      # 0). With the list collapsed there's no intrinsic-width content, so the
      # width floor now lives in CSS — `.splash { width:100% }` +
      # `.map-picker-wrap { min-width }` keep the picker map full-width when closed.
      tags$details(class = "site-browse",
        tags$summary(class = "site-browse-summary",
          tags$span(class = "sbs-label", bs_icon("list-ul"), " Browse all 46 sites"),
          tags$span(class = "sbs-chevron", bs_icon("chevron-down"))),
        div(class = "site-browse-body", uiOutput("siteCards"))))),

  # ---- main tabs ---------------------------------------------------------
  div(id = "mainTabsWrap", class = "main-tabs-wrap",
    navset_card_tab(id = "tabs",

      nav_panel(title = tagList(bs_icon("compass"), " Overview"), value = "overview",
        div(class = "home-nav",
          actionButton("goDiversity", tagList(bs_icon("diagram-3-fill"), div("Diversity"), tags$small("richness & species-area")), class = "home-btn"),
          actionButton("goInvasive", tagList(bs_icon("shield-exclamation"), div("Native vs Invasive"), tags$small("the invasion lens")), class = "home-btn home-btn-star"),
          actionButton("goExpected", tagList(bs_icon("clipboard-check"), div("Expected vs Observed"), tags$small("completeness & QC")), class = "home-btn"),
          actionButton("goLab", tagList(bs_icon("bullseye"), div("Diversity Lab"), tags$small("every plot, pinnable")), class = "home-btn"),
          actionButton("goPlot", tagList(bs_icon("flower1"), div("Plot Profile"), tags$small("drill into one plot")), class = "home-btn"),
          actionButton("goMap", tagList(bs_icon("map-fill"), div("Map"), tags$small("plots across the site")), class = "home-btn")),
        div(class = "tools-strip",
          actionButton("compareBtn", tagList(bs_icon("layout-split"), " Compare two sites"), class = "btn-outline-dark btn-sm"),
          downloadButton("allDataZip", "Download all data (CSV)", class = "btn-outline-dark btn-sm")),
        card(full_screen = TRUE,
          card_head("bar-chart-steps", "What covers the ground: most abundant plants",
            info_pop("Cover composition",
              p("Mean ", tags$b("relative cover per supported plot"), " for each species, from sampled 1 m² quadrats. Species absent from a supported plot contribute zero; bars are coloured ", tags$span(style="color:#1a7f37;font-weight:700","native"), " vs ", tags$span(style="color:#c1502e;font-weight:700","introduced"), "."),
              p("The current occurrence bundle cannot identify truly sampled-but-empty quadrats, so this corrects across known supported plots but does not invent unrecorded survey opportunities. Ocular layers overlap; values are not a percent of ground."))),
          uiOutput("overviewInsight"),
          spin(plotlyOutput("coverBar", height = "440px"))),
        card(card_head("stars", "The story so far",
            info_pop("Story", p("Written from this site's live data, the same numbers the rest of the app uses."))),
          uiOutput("siteInsights")),
        h4(class = "section-title", bs_icon("flower2"), " Ground cover here"),
        spin(plotlyOutput("groundBar", height = "260px"))),

      nav_menu(title = tagList(bs_icon("compass"), " Explore"),
      nav_panel(title = tagList(bs_icon("diagram-3-fill"), " Diversity"), value = "diversity",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("How diverse is this site?",
             info_pop("What richness is, and isn't",
               p("Richness counts ", tags$b("how many species"), " are present. It is composition, ", tags$b("not"), " productivity or ecosystem health."),
               p("Richness can rise through native additions, introduced additions, or both. Inspect composition and cover before assigning ecological meaning; more species ≠ more biomass or a healthier system."),
               p("For a standing-stock (productivity) signal, veg-structure basal area is the honest measure; this tab's richness reads composition."))),
          p("Richness across NEON's nested quadrat scales, the diversity profile, and a bias-corrected incidence lower-bound estimate of total richness."))),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE,
            card_head("graph-up", "Species–area curve (nested quadrats)",
              info_pop("Species-area",
                p("Mean species richness as sampled area grows from a 1 m² subplot → 10 m² → 100 m² corner → the 400 m² plot. NEON's nested design measures this directly."),
                p("The curve describes how mean richness changes across the measured grains. Its slope or apparent flattening at 400 m² does not by itself reveal total site richness or prove sampling completeness."))),
            uiOutput("saInsight"),
            div(class = "sizelab-toolbar",
              tags$button(class = "smt-snap-btn", type = "button",
                          onclick = "smtSave('saPlotBox','neon-plantdiv-species-area-<site>_<date>.png')",
                          bsicons::bs_icon("camera-fill"), " Download (with pins)"),
              tags$button(class = "smt-clear-btn", type = "button", onclick = "smtClearPins('saPlotBox')",
                          bsicons::bs_icon("eraser-fill"), " Clear pins")),
            div(class = "smt-pinnable", id = "saPlotBox", spin(plotlyOutput("saPlot", height = "360px")))),
          card(full_screen = TRUE,
            card_head("diagram-2", "Diversity profile (Hill numbers)",
              info_pop("Hill numbers",
                p("Three views in one unit, an ", tags$b("effective number of species"), " weighted by ", tags$em("q"), " (how much rare species count): q0 = richness, q1 = exp(Shannon) (common species), q2 = inverse Simpson (dominant species)."),
                p("When q1/q2 sit far below q0, a few species ", tags$b("dominate"), " the cover."))),
            uiOutput("hillInsight"),
            spin(plotlyOutput("hillPlot", height = "260px")))),
        card(card_head("calculator", "A lower bound on total richness (Chao2)",
            info_pop("Chao2",
              p(tags$b("Chao2"), " is an incidence-based, bias-corrected lower-bound estimate of total richness, calculated from how many species were seen in exactly one versus two subplots (Chao 1987). The difference between Chao2 and observed richness is the estimated unseen component, not a confirmed species count."),
              p("Incidence (presence across subplots), not cover, is the right input here. When species-seen-in-exactly-two are scarce it's unstable and flagged a lower bound."))),
          uiOutput("chaoBanner"))),

      nav_panel(title = tagList(bs_icon("shield-exclamation"), " Native vs Invasive"), value = "invasive",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Where does introduced cover warrant a closer look?"),
          p("Review introduced-cover composition, the species involved, and how their detections change across NEON's nested survey grains. These are monitoring leads—not proof of spread, impact, or management priority."))),
        card(full_screen = TRUE,
          card_head("graph-up-arrow", "Introduced cover across registered survey years",
            info_pop("Invaded cover",
              p("The share of relative vegetative cover contributed by ", tags$span(style="color:#c1502e;font-weight:700","introduced"), " species, computed from the same recurrent plot panel after selecting one deterministic survey bout per plot-year."),
              p("Status is NEON's ", tags$code("nativeStatusCode"), "; the % of species with ", tags$b("unknown"), " status is shown so you can judge how complete the picture is."))),
          uiOutput("invInsight"),
          spin(plotlyOutput("invTrend", height = "320px"))),
        layout_columns(col_widths = c(6, 6),
          card(full_screen = TRUE,
            card_head("exclamation-triangle-fill", "Invasive watchlist",
              info_pop("Watchlist", p("Introduced species ranked by mean 1 m² cover and the number of sampled plots where they were detected. High values are a transparent reason to review a species first, not a management prescription."))),
            spin(DT::DTOutput("invTable")),
            div(class = "sizelab-toolbar",
              downloadButton("watchlistCsv", "Download (CSV)", class = "smt-clear-btn"))),
          card(full_screen = TRUE,
            card_head("zoom-in", "Cross-scale occurrence: fine grain vs whole plot",
              info_pop("Cross-scale occurrence",
                p("Each dot is one introduced species—not one plot. The x-axis counts plots where the species was detected in sampled 1 m² quadrats; the y-axis counts plots where it appeared anywhere in the nested 400 m² plot."),
                p("A point above the 1:1 line is detected in more plots at broader survey grain than at 1 m². That can reflect detectability, spatial patchiness, or sampling support. It is not a temporal spread estimate."),
                p("Use the gap as a review-first index. Open a pinned card to see the exact plot lists before interpreting a species."))),
            div(class = "sizelab-toolbar",
              tags$button(class = "smt-snap-btn", type = "button",
                          onclick = "smtSave('pressurePlotBox','neon-plantdiv-cross-scale-occurrence-<site>_<date>.png')",
                          bsicons::bs_icon("camera-fill"), " Download (with pins)"),
              tags$button(class = "smt-clear-btn", type = "button", onclick = "smtClearPins('pressurePlotBox')",
                          bsicons::bs_icon("eraser-fill"), " Clear pins"),
              tags$span(class = "sizelab-hint", bs_icon("hand-index-thumb"), " tap to pin · then choose ‘Where is it?’")),
            div(class = "smt-pinnable", id = "pressurePlotBox", spin(plotlyOutput("pressurePlot", height = "360px"))))) )
      ),

      nav_menu(title = tagList(bs_icon("clipboard-check"), " Network & QC"),
      nav_panel(title = tagList(bs_icon("clipboard-check"), " Expected vs Observed"), value = "expected",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("What should grow here, and what did NEON find?",
            info_pop("Expected vs Observed",
              p(tags$b("Expected"), " = a reference plant-community list resolved from one soil unit near the site's reference point. It is context for the sampled plots, not a complete site-wide flora."),
              p("NEON samples a small plot area (~400 m² per plot) at peak greenness, so a species ", tags$b("expected but not found"), " usually means it just wasn't in the sampled patch, ", tags$b("not"), " that anything is wrong."),
              p("The ", tags$b("review"), " list is where a second look pays off: a plant NEON recorded that the reference community doesn't list (a new invader, a range edge, or a possible mis-ID)."))),
          p(HTML("<b>Reference context</b> comes from one NRCS ecological-site lookup near the site centre. It helps assess list completeness; it does not define every plot or declare observations wrong.")))),

        uiOutput("evoHeader"),
        uiOutput("evoHeadline"),
        uiOutput("evoCoarse"),

        # A — confirmation (green)
        card(full_screen = TRUE, class = "evo-bucket evo-card evo-a",
          card_head("check2-circle", "Reference flora detected here",
            info_pop("Bucket A · expected & observed",
              p("Species the NEON crews recorded that are also on the NRCS reference list for this ecological site, the overlap that confirms the site is what the soil survey says it is."),
              p("Sorted by the reference community's expected production (the species you'd most expect to dominate float to the top)."))),
          div(class = "evo-dl-row",
            downloadButton("evoCsvA", "Download (CSV + codebook ZIP)", class = "smt-clear-btn")),
          div(class = "evo-tbl-wrap", DT::DTOutput("evoTableA", width = "100%"))),

        # C — the review lane (clay)
        card(full_screen = TRUE, class = "evo-bucket evo-card evo-c",
          card_head("search", "Observed here, not in the reference list, worth a look",
            info_pop("Bucket C · observed, not expected",
              p("Plants NEON recorded that the NRCS reference community for this ecological site does not list. Two very different stories live here:"),
              tags$ul(
                tags$li(HTML("<b>Introduced</b>, useful composition context for the Native-vs-Invasive lens.")),
                tags$li(HTML("<b>Native or unknown</b>, often a range edge, a finer identification than the reference used, a different plot soil unit, or an incomplete reference list."))),
              p("Every observed-but-unlisted record stays visible for review. The current bundle does not use undocumented state-occurrence matching to silently demote records."),
              p("Labelled “review”, never “error”. Gaps in the reference list are real and common."))),
          div(class = "evo-subhead", bs_icon("info-circle"),
            HTML("A <b>completeness and review</b> instrument, not an error detector. These taxa occurred in NEON records but are not on the single-point reference list bundled for this site.")),
          div(class = "evo-dl-row",
            downloadButton("evoCsvC", "Download (CSV + codebook ZIP)", class = "smt-clear-btn")),
          div(class = "evo-tbl-wrap", DT::DTOutput("evoTableC", width = "100%"))),

        # B — completeness (neutral, never red)
        card(full_screen = TRUE, class = "evo-bucket evo-card evo-b",
          card_head("clipboard-data", "Expected but not detected: a completeness view",
            info_pop("Bucket B · expected but absent",
              p("Reference species NEON did ", tags$b("not"), " detect in its plots. This is overwhelmingly ", tags$b("non-detection"), ": NEON samples ~400 m² per plot, while an ecological site lists the whole site's potential vegetation under reference conditions."),
              p("It can also be a legitimate ", tags$b("state transition"), " (e.g. a shrub-encroached desert grassland). Read it as completeness or as an ecological pattern, ", tags$b("never as missing data or error.")),
              p("Sorted by expected production; the ", tags$b("reference dominants"), " not detected are shown in bold, the most informative gaps."))),
          div(class = "evo-subhead", bs_icon("info-circle"),
            "Not a problem list. NEON samples ~400 m² per plot, so these are mostly species just outside the sampled patch."),
          div(class = "evo-dl-row",
            downloadButton("evoCsvB", "Download (CSV + codebook ZIP)", class = "smt-clear-btn")),
          div(class = "evo-tbl-wrap", DT::DTOutput("evoTableB", width = "100%"))),

        # data-quality cross-checks (the true-QC lane) — needs only occ, so it stays
        # visible even when no reference list is bundled for the site
        card(class = "evo-card",
          card_head("clipboard-pulse", "Data-quality cross-checks",
            info_pop("True QC",
              p("Two genuine data-quality signals, kept separate from the completeness view above (these don't need a reference list):"),
              tags$ul(
                tags$li(HTML("<b>Nativity review</b>, including contradictory NEON statuses and—within its valid geographic scope—disagreement with USDA PLANTS.")),
                tags$li(HTML("<b>Implausible cover</b>, total cover in one 1 m² quadrat far exceeding what overlapping canopy layers explain (an entry-error backstop)."))))),
          div(class = "evo-dl-row",
            downloadButton("evoReport", tagList(bs_icon("download"), " Full report (CSV + codebook ZIP)"), class = "smt-snap-btn")),
          uiOutput("evoFlags"))),

      nav_panel(title = tagList(bs_icon("cloud-sun"), " Short-record context"), value = "environment",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("How do the short annual records move together?"),
          p("Place each registered annual plant estimate beside complete co-located climate or phenology years. This is descriptive short-record context—not a fitted ecological driver and not an input to Driver Cascade."))),
        div(class = "env-pop-bar",
          div(class = "env-pop-row",
            div(class = "env-pop-sel",
              selectInput("envMetric", tagList(bs_icon("flower1"), " Plant signal"),
                          choices = c("Species richness (diversity)" = "richness",
                                      "% introduced cover" = "pct_introduced",
                                      "Total cover" = "total_cover"),
                          selected = "richness", width = "100%")),
            div(class = "env-pop-sel",
              selectInput("envLayer", tagList(bs_icon("cloud-sun"), " Context series"),
                          choices = c("Largest screened association" = "best"), selected = "best", width = "100%")))),
        uiOutput("envSourceNote"),
        uiOutput("envCorrNote"),
        uiOutput("envCaveat"),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE,
            card_head("graph-up", "Plant estimate vs context series, by survey year",
              info_pop("Reading this",
                p("Each point is one survey year: the registered plant estimate (y) against a complete annual context value (x), at the screened lag with the largest rank-correlation."),
                p("No fitted line is drawn. With this few annual points, a line would imply more stability than the record supports; inspect the points, support, and permutation result together."))),
            spin(plotlyOutput("envScatter", height = "360px"))),
          card(full_screen = TRUE,
            card_head("bar-chart-steps", "Screened associations",
              info_pop("Association scan",
                p("Spearman |r| for each context series at its screened lag (0–2 yr). With “Largest screened association” selected, the circular-shift p corrects the full series × lag screen; with one series selected, it corrects that series's lag screen only. The bars are ", tags$b("not independent evidence"), ", and on a short record none may be distinguishable from chance."))),
            spin(plotlyOutput("envDriverRank", height = "360px")))),
        card(card_head("calendar3", "Raw annual histories",
            info_pop("Context",
              p("The registered plant estimate (left axis) and selected context series (right axis) on their original calendar years."),
              p("This view does not apply the screened lag or restrict to the matched correlation rows. Use the scatter and Matched series CSV for the alignment behind the reported association."))),
          spin(plotlyOutput("envTrend", height = "300px"))),
        div(class = "env-export-row",
          tags$span(class = "env-export-lab", bs_icon("download"), " Take the numbers with you:"),
          downloadButton("envSeriesCsv", "Matched series (CSV)", class = "smt-clear-btn"),
          downloadButton("envRankCsv", "Association scan + lag-corrected p (CSV)", class = "smt-clear-btn"))),

      # ---- Search the network -------------------------------------------------
      # Queries a small precomputed index (data/search_index.rds) loaded once at
      # boot — no live fetch, instant. Two modes: find a species across sites, or
      # filter sites by introduced-cover threshold. Both jump to a site's Overview.
      nav_panel(title = tagList(bs_icon("search"), " Search"), value = "search",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Search the network"),
          p("Look across every bundled NEON site at once. Find which sites a plant turns up at, or pull the sites by how invaded they are. This reads a small index built into the app, so it answers instantly without fetching anything."))),
        div(class = "search-modebar",
          radioButtons("searchMode", NULL, inline = TRUE,
                       choices = c("Find a species" = "taxon",
                                   "Filter sites by cover" = "threshold"),
                       selected = "taxon")),

        conditionalPanel("input.searchMode == 'taxon'",
          layout_columns(col_widths = c(5, 7),
            card(card_head("flower2", "Pick a species"),
              p(class = "dim", style = "margin:0 0 10px",
                "Start typing a scientific name. The list holds every species recorded at any bundled site."),
              selectizeInput("searchTaxon", NULL, choices = NULL, width = "100%",
                             options = list(placeholder = "e.g. Eragrostis lehmanniana",
                                            maxOptions = 1000)),
              uiOutput("searchTaxonMeta")),
            card(full_screen = TRUE,
              card_head("geo-alt", "Where it occurs",
                info_pop("Reading this",
                  p("One row per site where this species was recorded, with the site's mean 1 m^2 percent cover for it and the years it was seen. Cover is a ", tags$b("within-site index"), ", not an absolute ranking across sites."))),
              uiOutput("searchTaxonCount"),
              div(style = "width:100%", DTOutput("searchTaxonTbl"))))),

        conditionalPanel("input.searchMode == 'threshold'",
          layout_columns(col_widths = c(5, 7),
            card(card_head("sliders", "Set the filter"),
              radioButtons("threshNativity", "Cover of",
                           choices = c("Introduced" = "Introduced", "Native" = "Native"),
                           selected = "Introduced", inline = TRUE),
              div(class = "thresh-row",
                selectInput("threshDir", "is", width = "120px",
                            choices = c("at least" = "ge", "at most" = "le"), selected = "ge"),
                numericInput("threshPct", "% of site cover", value = 10, min = 0, max = 100, step = 5, width = "150px")),
              tags$hr(),
              p(class = "dim", style = "margin:0 0 8px", "Or jump straight to a known invader:"),
              selectizeInput("threshInvader", "Find an introduced species", choices = NULL, width = "100%",
                             options = list(placeholder = "e.g. Bromus tectorum", maxOptions = 1000))),
            card(full_screen = TRUE,
              card_head("list-ul", "Matching sites",
                info_pop("Reading this",
                  p("Sites are ranked by the chosen cover share. These shares are ", tags$b("within-site indices"), " built the same way as each site's hero number, so a high % means a site that is heavily invaded relative to its own cover, not the most invaded acre in the network."))),
              uiOutput("searchThreshCount"),
              div(style = "width:100%", DTOutput("searchThreshTbl"))))),

        p(class = "dim", style = "margin-top:14px;font-size:12px",
          "Percent cover is a relative within-site index from the 1 m^2 quadrats (space-for-time, not an absolute or census number). Pick a site and press Explore to load it into every other tab."))
      ),

      nav_menu(title = tagList(bs_icon("grid-3x3-gap"), " Plots"),
      nav_panel(title = tagList(bs_icon("bullseye"), " Diversity Lab"), value = "lab",
        div(class = "tab-head",
          div(class = "tab-head-text",
            h4("Every plot on one map",
               info_pop("Diversity Lab",
                 p("Each dot is a ", tags$b("plot"), ", placed by its ", tags$b("species richness"), " (x) and the ", tags$b("share of its cover that's introduced"), " (y). Median crosshairs split it into four corners."),
                 p(tags$b("Tap a dot"), " to pin its card; drag it, resize it, and ", tags$b("download the chart with the cards on it"), ". Tap “Open plot profile” for the full drill-down."))),
            p("Each dot is a plot: richness × how invaded it is. Tap to pin a card; open any plot's full profile.")),
          div(class = "sizelab-controls",
            selectInput("labColor", tagList(bs_icon("palette"), " Colour by"),
                        choices = c("Habitat (NLCD)" = "nlcdClass", "Plot type" = "plotType",
                                    "Dominant family" = "domfam"), selected = "nlcdClass", width = "220px"))),
        card(full_screen = TRUE,
          card_head("bullseye", "Richness × introduced-cover, by plot",
            info_pop("Reading this",
              p("Left = fewer species; right = more species; top = more introduced cover; bottom = native-dominated cover. The ", tags$span(style="color:#c9a300;font-weight:700","gold diamond"), " is the plot you're viewing."),
              p("More species (right) is ", tags$b("not"), " automatically better: richness is composition, not condition. Read the x-axis together with native, introduced, and unknown-status cover."),
              p(tags$b("What a pattern means."), " Each dot is one plot. A downward, flat, or upward cloud describes how 400 m² richness and the relative introduced-cover index co-vary in this snapshot. Plausible explanations include habitat differences, observation support, disturbance history, and composition change; this chart does not choose among them."),
              p(tags$b("The honest caveats."), " This is a cross-sectional review lead, not a causal slope. The y-axis comes from overlapping ocular estimates in represented 1 m² quadrats, not a fraction of bare ground. A plot at 30% introduced cover has not necessarily lost 30% of its ground to introduced plants."))),
          div(class = "sizelab-toolbar",
            tags$button(class = "smt-snap-btn", type = "button",
                        onclick = "smtSave('labScatterBox','neon-plantdiv-diversity-lab-<site>_<date>.png')",
                        bsicons::bs_icon("camera-fill"), " Download (with pinned cards)"),
            tags$button(class = "smt-clear-btn", type = "button", onclick = "smtClearPins('labScatterBox')",
                        bsicons::bs_icon("eraser-fill"), " Clear pins"),
            tags$span(class = "sizelab-hint", bs_icon("hand-index-thumb"), " interactive · tap a dot to pin its card")),
          div(class = "smt-pinnable", id = "labScatterBox", spin(plotlyOutput("labScatter", height = "540px")))),
        tags$details(class = "lab-table-details",
          tags$summary(bs_icon("table"), " Accessible plot table"),
          p(class = "dim", "The same plot-level values in a sortable table, with a direct Open profile action."),
          DT::DTOutput("labTable")),
        uiOutput("plotCardSlot")),

      nav_panel(title = tagList(bs_icon("flower1"), " Plot Profile"), value = "plot",
        uiOutput("plotProfile")),

      nav_panel(title = tagList(bs_icon("map-fill"), " Map"), value = "map",
        div(class = "tab-head",
          div(class = "tab-head-text",
            h4("Plots across the site"),
            p("Each marker is a NEON plot, sized by richness and coloured by how invaded it is. The selected plot glows gold.")),
          div(class = "map-controls",
            selectInput("mapMetric", "Colour by", width = "180px",
                        choices = c("% introduced cover" = "pct_introduced", "Species richness" = "richness")),
            selectInput("view", "Basemap", width = "160px",
                        choices = c("Satellite" = "Esri.WorldImagery", "Terrain" = "Esri.WorldTopoMap",
                                    "Light" = "CartoDB.Positron")))),
        spin(leafletOutput("map", height = "620px")))
      ),

      nav_panel(title = tagList(bs_icon("info-circle"), " About"), value = "about",
        uiOutput("aboutPanel"))
    ))),

  div(class = "ddl-footer",
    div(tags$a(class = "custom-cta",
      href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Plant%20Diversity%20Explorer",
      span(class = "hand", "\U0001F44B"), "Questions or feedback? Get in touch with Desert Data Labs.")),
    p(style = "margin-top:12px",
      HTML("Built by <strong>Desert Data Labs</strong> · Tucson, AZ · get in touch →"),
      tags$a(href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Plant%20Diversity%20Explorer", "desertdatalabs@gmail.com")),
    p(style = "font-size:12px;opacity:.85",
      "Data: NEON Plant Presence & Percent Cover (DP1.10058.001). Not affiliated with NEON, Battelle, or the NSF. An educational data-exploration tool."))
)
