# ===========================================================================
# NEON Plant Diversity Explorer — ui.R
# ===========================================================================

# rarity-style tier badge for plots (richness-based) — reused look from the flagship
tier_badge <- function(label, color) tags$span(class = "tag-badge",
  style = sprintf("background:%s;border-color:%s;color:#fff", color, color), label)

ui <- bslib::page_sidebar(
  theme = app_theme, title = NULL,
  window_title = "NEON Plant Diversity Explorer", fillable = FALSE,

  tags$head(
    tags$link(rel = "preconnect", href = "https://fonts.googleapis.com"),
    tags$link(rel = "preconnect", href = "https://fonts.gstatic.com", crossorigin = NA),
    tags$link(rel = "stylesheet",
      href = "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500..800&family=Rubik:wght@400;500;600;700;800&display=swap"),
    tags$link(rel = "stylesheet", href = "https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.min.css"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.all.min.js"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/html-to-image@1.11.11/dist/html-to-image.js"),
    tags$link(rel = "stylesheet", href = asset_url("styles.css")),
    tags$link(rel = "stylesheet", href = asset_url("plant.css")),
    tags$script(src = asset_url("app.js")),
    tags$script(src = asset_url("pincards.js"))
  ),
  useShinyjs(),

  # ---- sidebar -----------------------------------------------------------
  sidebar = sidebar(
    width = 320, class = "control-deck",
    div(class = "brand",
      div(class = "brand-mark", "\U0001F33F"),
      div(div(class = "brand-title", "Plant Diversity Explorer"),
          div(class = "brand-sub", "NEON field observatory"))),

    selectInput("stateSel", label = tagList(bs_icon("geo-alt-fill"), " 1 · Pick a state"),
                choices = NULL, width = "100%"),
    selectInput("site", label = tagList(bs_icon("pin-map-fill"), " 2 · Pick a site"),
                choices = NULL, width = "100%"),
    uiOutput("siteBio"),

    actionButton("loadBtn", tagList(bs_icon("globe-americas"), " Explore this site"),
                 class = "btn-primary btn-lg w-100 load-btn", onclick = "smtLoadStart()"),
    actionButton("demoBtn", tagList(bs_icon("stars"), " or open the Santa Rita demo (instant)"),
                 class = "btn-link btn-sm w-100 reset-demo",
                 onclick = "smtLoadStart('Santa Rita — demo dataset')"),

    hidden(div(id = "plotPickerWrap",
      hr(class = "deck-hr"),
      selectizeInput("plotSel", label = tagList(bs_icon("search"), " Open a plot's profile"),
                     choices = NULL, options = list(placeholder = "Pick a plot…")),
      actionButton("surpriseBtn", tagList(bs_icon("dice-5-fill"), " Surprise me"),
                   class = "btn-outline-dark btn-sm w-100"))),

    hr(class = "deck-hr"),
    actionButton("help", tagList(bs_icon("question-circle"), " How it works"),
                 class = "btn-outline-dark btn-sm w-100"),
    div(class = "theme-toggle-row",
      tags$span(class = "theme-toggle-lab", bs_icon("circle-half"), " Theme"),
      input_dark_mode(id = "colorMode", mode = "light")),
    div(class = "deck-foot",
      bs_icon("database"), " NEON ", tags$code("DP1.10058.001"),
      br(), tags$a(href = "https://desertdatalabs.com", target = "_blank",
                   bs_icon("box-arrow-up-right"), " Desert Data Labs"))
  ),

  # ---- loading overlay ---------------------------------------------------
  div(id = "loadOverlay", class = "load-overlay",
    div(class = "load-card",
      div(class = "load-spin", "\U0001F33F"),
      div(class = "load-title", "Loading site data"),
      div(id = "loadSite", class = "load-site"),
      div(class = "load-bar"),
      div(class = "load-note", "Building the diversity profiles, cover maps, and charts."))),

  uiOutput("heroStats"),

  # ---- splash ------------------------------------------------------------
  div(id = "splash",
    div(class = "splash",
      div(class = "app-hero app-hero-splash",
        h1(class = "app-title", "NEON Plant Diversity Explorer",
           span(class = "title-tag", "unofficial")),
        p(class = "app-subtitle",
          "A field guide to what grows where NEON samples — how rich each site is, what covers the ground, and where introduced plants are gaining a foothold. Built on the nested-quadrat plant survey (DP1.10058.001).")),
      p("Tap a ", tags$b("site"), " on the map — dot size is species richness — or step into the Santa Rita demo (a Sonoran desert grassland with a textbook Lehmann-lovegrass invasion)."),
      div(class = "splash-colorby",
        radioButtons("splashColorBy", label = NULL, inline = TRUE,
          choices = c("Colour: invasion" = "invasion", "Colour: completeness" = "completeness"),
          selected = "invasion"),
        uiOutput("splashLegend")),
      mapPickerUI("picker", height = "520px", spinner = DDL$green),
      div(class = "picker-actions", style = "margin:14px 0",
        actionButton("demoBtn2", tagList(bs_icon("stars"), " Open the Santa Rita demo instantly"),
                     class = "btn-primary btn-lg", onclick = "smtLoadStart('Santa Rita — demo dataset')")),
      # site-card grid stays VISIBLE below the map: it has intrinsic width, so it
      # keeps the splash column from shrink-wrapping to 0 (the width-less leaflet
      # alone would collapse it), and doubles as the "pick from a list" path.
      div(class = "site-list-block",
        tags$div(class = "site-list-head", bs_icon("list-ul"), " or pick from the full site list"),
        uiOutput("siteCards")))),

  # ---- main tabs ---------------------------------------------------------
  div(id = "mainTabsWrap", class = "main-tabs-wrap",
    navset_card_tab(id = "tabs",

      nav_panel(title = tagList(bs_icon("compass"), " Overview"), value = "overview",
        div(class = "home-nav",
          actionButton("goDiversity", tagList(bs_icon("diagram-3-fill"), div("Diversity"), tags$small("richness & species-area")), class = "home-btn"),
          actionButton("goInvasive", tagList(bs_icon("shield-exclamation"), div("Native vs Invasive"), tags$small("the invasion lens")), class = "home-btn home-btn-star"),
          actionButton("goExpected", tagList(bs_icon("clipboard-check"), div("Expected vs Observed"), tags$small("completeness & QC")), class = "home-btn"),
          actionButton("goLab", tagList(bs_icon("bullseye"), div("Diversity Lab"), tags$small("every plot, pinnable")), class = "home-btn"),
          actionButton("goPlot", tagList(bs_icon("flower1"), div("Plot Profile"), tags$small("drill into one plot")), class = "home-btn"),
          actionButton("goMap", tagList(bs_icon("map-fill"), div("Map"), tags$small("plots across the site")), class = "home-btn")),
        div(class = "tools-strip",
          actionButton("compareBtn", tagList(bs_icon("layout-split"), " Compare two sites"), class = "btn-outline-dark btn-sm"),
          downloadButton("allDataZip", "Download all data (CSV)", class = "btn-outline-dark btn-sm"),
          downloadButton("reportPdf", "Site report (PDF)", class = "btn-outline-dark btn-sm")),
        card(full_screen = TRUE,
          card_head("bar-chart-steps", "What covers the ground — most abundant plants",
            info_pop("Cover composition",
              p("Mean ", tags$b("percent cover"), " per species, from the 1 m² quadrats, summed across the site. Bars are coloured ", tags$span(style="color:#1a7f37;font-weight:700","native"), " vs ", tags$span(style="color:#c1502e;font-weight:700","introduced"), "."),
              p("Cover is an ocular estimate and vegetation layers overlap, so site-summed cover is a relative measure, not a percentage of ground."))),
          uiOutput("overviewInsight"),
          spin(plotlyOutput("coverBar", height = "440px"))),
        card(card_head("stars", "The story so far",
            info_pop("Story", p("Written from this site's live data — the same numbers the rest of the app uses."))),
          uiOutput("siteInsights")),
        h4(class = "section-title", bs_icon("flower2"), " Ground cover here"),
        spin(plotlyOutput("groundBar", height = "260px"))),

      nav_panel(title = tagList(bs_icon("diagram-3-fill"), " Diversity"), value = "diversity",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("How diverse is this site?"),
          p("Richness across NEON's nested quadrat scales, the diversity profile, and a bias-corrected estimate of how many species are really out there."))),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE,
            card_head("graph-up", "Species–area curve (nested quadrats)",
              info_pop("Species-area",
                p("Mean species richness as sampled area grows from a 1 m² subplot → 10 m² → 100 m² corner → the 400 m² plot. NEON's nested design measures this directly."),
                p("A curve still climbing steeply at 400 m² means the site is ", tags$b("undersampled"), " — there's more out there than the plots have caught."))),
            uiOutput("saInsight"),
            spin(plotlyOutput("saPlot", height = "360px"))),
          card(full_screen = TRUE,
            card_head("diagram-2", "Diversity profile (Hill numbers)",
              info_pop("Hill numbers",
                p("Three views in one unit — an ", tags$b("effective number of species"), " weighted by ", tags$em("q"), " (how much rare species count): q0 = richness, q1 = exp(Shannon) (common species), q2 = inverse Simpson (dominant species)."),
                p("When q1/q2 sit far below q0, a few species ", tags$b("dominate"), " the cover."))),
            uiOutput("hillInsight"),
            spin(plotlyOutput("hillPlot", height = "260px")))),
        card(card_head("calculator", "How many species are really here? (Chao2)",
            info_pop("Chao2",
              p(tags$b("Chao2"), " is an incidence-based, bias-corrected ", tags$b("minimum"), " estimate of total richness — a floor that includes species the plots haven't caught yet, from how many species were seen in exactly one vs two subplots (Chao 1987)."),
              p("Incidence (presence across subplots), not cover, is the right input here. When species-seen-in-exactly-two are scarce it's unstable and flagged a lower bound."))),
          uiOutput("chaoBanner"))),

      nav_panel(title = tagList(bs_icon("shield-exclamation"), " Native vs Invasive"), value = "invasive",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Where are introduced plants gaining ground?"),
          p("The plant-monitoring signal land managers act on: how much of the cover is introduced, which species, and — using the nested design — where invasion is getting a foothold at the finest scale."))),
        card(full_screen = TRUE,
          card_head("graph-up-arrow", "Introduced cover share, over time",
            info_pop("Invaded cover",
              p("The share of total vegetative cover contributed by ", tags$span(style="color:#c1502e;font-weight:700","introduced"), " species, by year."),
              p("Status is NEON's ", tags$code("nativeStatusCode"), "; the % of species with ", tags$b("unknown"), " status is shown so you can judge how complete the picture is."))),
          uiOutput("invInsight"),
          spin(plotlyOutput("invTrend", height = "320px"))),
        layout_columns(col_widths = c(6, 6),
          card(full_screen = TRUE,
            card_head("exclamation-triangle-fill", "Invasive watchlist",
              info_pop("Watchlist", p("Introduced species ranked by mean 1 m² cover and how many plots they reach. The widespread, high-cover ones are the management priority."))),
            spin(DT::DTOutput("invTable"))),
          card(full_screen = TRUE,
            card_head("zoom-in", "Invasion-pressure index — the foothold detector",
              info_pop("Invasion pressure",
                p("A NEONize original. Because richness is measured at every nested scale, we can ask: how many introduced species are already detectable at the ", tags$b("smallest (1 m²)"), " scale, where they're cheap to catch but scary to a manager?"),
                p("Each dot is a plot: introduced species found at 1 m² (x) vs across the whole 400 m² plot (y). Plots high on x have invaders established right down to the finest grain."))),
            spin(plotlyOutput("pressurePlot", height = "360px")))) ),

      nav_panel(title = tagList(bs_icon("clipboard-check"), " Expected vs Observed"), value = "expected",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("What should grow here — and what did NEON find?",
            info_pop("Expected vs Observed",
              p(tags$b("Expected"), " = the plants the NRCS Ecological Site lists for this kind of soil and climate (its reference plant community), resolved from the site's coordinates."),
              p("NEON samples a small plot area (~400 m² per plot) at peak greenness, so a species ", tags$b("expected but not found"), " usually means it just wasn't in the sampled patch — ", tags$b("not"), " that anything is wrong."),
              p("The ", tags$b("review"), " list is where a second look pays off: a plant NEON recorded that the reference community doesn't list (a new invader, a range edge, or a possible mis-ID)."))),
          p(HTML("<b>Expected</b> = the plants NRCS says this soil &amp; climate can support (its ecological site reference community). The one lane worth a second look is <b>observed-but-unexpected</b>; the rest is confirmation and completeness.")))),

        uiOutput("evoHeader"),
        uiOutput("evoHeadline"),
        uiOutput("evoCoarse"),

        # A — confirmation (green)
        card(full_screen = TRUE, class = "evo-bucket evo-card evo-a",
          card_head("check2-circle", "Reference flora detected here",
            info_pop("Bucket A — expected & observed",
              p("Species the NEON crews recorded that are also on the NRCS reference list for this ecological site — the overlap that confirms the site is what the soil survey says it is."),
              p("Sorted by the reference community's expected production (the species you'd most expect to dominate float to the top)."))),
          div(class = "evo-dl-row",
            downloadButton("evoCsvA", "Download (CSV)", class = "smt-clear-btn")),
          div(class = "evo-tbl-wrap", DT::DTOutput("evoTableA", width = "100%"))),

        # C — the review lane (clay)
        card(full_screen = TRUE, class = "evo-bucket evo-card evo-c",
          card_head("search", "Observed here, not in the reference list — worth a look",
            info_pop("Bucket C — observed, not expected",
              p("Plants NEON recorded that the NRCS reference community for this ecological site does not list. Two very different stories live here:"),
              tags$ul(
                tags$li(HTML("<b>Introduced</b> — an invasion signal; ties to the Native-vs-Invasive lens.")),
                tags$li(HTML("<b>Native, not in reference</b> — most often just a real associate the reference list didn't enumerate (these lists are representative, not exhaustive); sometimes a range edge, a finer ID than the soil survey used, or (rarely) a mis-ID."))),
              p("Labelled “review”, never “error” — gaps in the reference list are real and common."))),
          div(class = "evo-dl-row",
            downloadButton("evoCsvC", "Download (CSV)", class = "smt-clear-btn")),
          div(class = "evo-tbl-wrap", DT::DTOutput("evoTableC", width = "100%"))),

        # B — completeness (neutral, never red)
        card(full_screen = TRUE, class = "evo-bucket evo-card evo-b",
          card_head("clipboard-data", "Expected but not detected — a completeness view",
            info_pop("Bucket B — expected but absent",
              p("Reference species NEON did ", tags$b("not"), " detect in its plots. This is overwhelmingly ", tags$b("non-detection"), ": NEON samples ~400 m² per plot, while an ecological site lists the whole site's potential vegetation under reference conditions."),
              p("It can also be a legitimate ", tags$b("state transition"), " (e.g. a shrub-encroached desert grassland). Read it as completeness or as an ecological pattern — ", tags$b("never as missing data or error.")),
              p("Sorted by expected production; the ", tags$b("reference dominants"), " not detected are shown in bold — the most informative gaps."))),
          div(class = "evo-subhead", bs_icon("info-circle"),
            "Not a problem list — NEON samples ~400 m² per plot, so these are mostly species just outside the sampled patch."),
          div(class = "evo-dl-row",
            downloadButton("evoCsvB", "Download (CSV)", class = "smt-clear-btn")),
          div(class = "evo-tbl-wrap", DT::DTOutput("evoTableB", width = "100%"))),

        # data-quality cross-checks (the true-QC lane) — needs only occ, so it stays
        # visible even when no reference list is bundled for the site
        card(class = "evo-card",
          card_head("clipboard-pulse", "Data-quality cross-checks",
            info_pop("True QC",
              p("Two genuine data-quality signals, kept separate from the completeness view above (these don't need a reference list):"),
              tags$ul(
                tags$li(HTML("<b>Nativity disagreement</b> — NEON's native/introduced label differs from USDA PLANTS for the same species.")),
                tags$li(HTML("<b>Implausible cover</b> — total cover in one 1 m² quadrat far exceeding what overlapping canopy layers explain (an entry-error backstop)."))))),
          div(class = "evo-dl-row",
            downloadButton("evoReport", tagList(bs_icon("download"), " Full report (CSV)"), class = "smt-snap-btn")),
          uiOutput("evoFlags"))),

      nav_panel(title = tagList(bs_icon("cloud-sun"), " Environment"), value = "environment",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Does the vegetation track the climate?"),
          p("Each survey year's plant signal against that year's climate and phenology, from co-located NEON sensors at this site. Plant surveys are annual and these records are short, so read this as ", tags$b("exploratory"), " — the permutation test says how easily chance alone could explain the link."))),
        div(class = "env-pop-bar",
          div(class = "env-pop-row",
            div(class = "env-pop-sel",
              selectInput("envMetric", tagList(bs_icon("flower1"), " Plant signal"),
                          choices = c("Species richness (diversity)" = "richness",
                                      "% introduced cover" = "pct_introduced",
                                      "Total cover" = "total_cover"),
                          selected = "richness", width = "100%")),
            div(class = "env-pop-sel",
              selectInput("envLayer", tagList(bs_icon("cloud-sun"), " Climate / phenology driver"),
                          choices = c("Strongest driver" = "best"), selected = "best", width = "100%")))),
        uiOutput("envSourceNote"),
        uiOutput("envCorrNote"),
        uiOutput("envCaveat"),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE,
            card_head("graph-up", "Plant signal vs the driver, by survey year",
              info_pop("Reading this",
                p("Each point is one survey year: the plant signal (y) against that year's driver value (x), at the lag with the strongest rank-correlation."),
                p("The dashed line is the fit. On this few points the ", tags$b("shape"), " (a relationship, or none) matters more than the exact r."))),
            spin(plotlyOutput("envScatter", height = "360px"))),
          card(full_screen = TRUE,
            card_head("bar-chart-steps", "Which driver does it track best?",
              info_pop("Driver ranking",
                p("Spearman |r| for each driver at its best lag (0–2 yr). These bars ARE the search the permutation test corrects for — they are ", tags$b("not independent evidence"), ", and on a short record none may be distinguishable from chance."))),
            spin(plotlyOutput("envDriverRank", height = "360px")))),
        card(card_head("calendar3", "The two series over time",
            info_pop("Context", p("The plant signal (left axis) and the selected driver (right axis) across the years — the raw movement behind the correlation."))),
          spin(plotlyOutput("envTrend", height = "300px")))),

      nav_panel(title = tagList(bs_icon("bullseye"), " Diversity Lab"), value = "lab",
        div(class = "tab-head",
          div(class = "tab-head-text",
            h4("Every plot on one map",
               info_pop("Diversity Lab",
                 p("Each dot is a ", tags$b("plot"), ", placed by its ", tags$b("species richness"), " (x) and the ", tags$b("share of its cover that's introduced"), " (y). Median crosshairs split it into four corners."),
                 p(tags$b("Tap a dot"), " to pin its card; drag it, resize it, and ", tags$b("download the chart with the cards on it"), ". Tap “Open plot profile” for the full drill-down."))),
            p("Each dot is a plot — richness × how invaded it is. Tap to pin a card; open any plot's full profile.")),
          div(class = "sizelab-controls",
            selectInput("labColor", tagList(bs_icon("palette"), " Colour by"),
                        choices = c("Habitat (NLCD)" = "nlcdClass", "Plot type" = "plotType",
                                    "Dominant family" = "domfam"), selected = "nlcdClass", width = "220px"))),
        card(full_screen = TRUE,
          card_head("bullseye", "Richness × introduced-cover, by plot",
            info_pop("Reading this", p("Top-left = species-poor but invaded; top-right = rich but invaded; bottom-right = the prize (rich & native); bottom-left = sparse native. The ", tags$span(style="color:#c9a300;font-weight:700","gold diamond"), " is the plot you're viewing."))),
          div(class = "sizelab-toolbar",
            tags$button(class = "smt-snap-btn", type = "button", onclick = "smtSaveScatter()",
                        bsicons::bs_icon("camera-fill"), " Download (with pinned cards)"),
            tags$button(class = "smt-clear-btn", type = "button", onclick = "smtClearPins()",
                        bsicons::bs_icon("eraser-fill"), " Clear pins"),
            tags$span(class = "sizelab-hint", bs_icon("hand-index-thumb"), " interactive · tap a dot to pin its card")),
          div(class = "smt-pinnable", spin(plotlyOutput("labScatter", height = "540px")))),
        uiOutput("plotCardSlot")),

      nav_panel(title = tagList(bs_icon("flower1"), " Plot Profile"), value = "plot",
        uiOutput("plotProfile")),

      nav_panel(title = tagList(bs_icon("map-fill"), " Map"), value = "map",
        div(class = "tab-head",
          div(class = "tab-head-text",
            h4("Plots across the site"),
            p("Each marker is a NEON plot, sized by richness and coloured by how invaded it is. The selected plot glows gold.")),
          div(class = "map-controls",
            selectInput("mapMetric", "Colour by", width = "180px",
                        choices = c("% introduced cover" = "pct_introduced", "Species richness" = "richness")),
            selectInput("view", "Basemap", width = "160px",
                        choices = c("Satellite" = "Esri.WorldImagery", "Terrain" = "Esri.WorldTopoMap",
                                    "Light" = "CartoDB.Positron")))),
        spin(leafletOutput("map", height = "620px"))),

      nav_panel(title = tagList(bs_icon("info-circle"), " About"), value = "about",
        uiOutput("aboutPanel"))
    )),

  div(class = "ddl-footer",
    div(tags$a(class = "custom-cta",
      href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Plant%20Diversity%20Explorer",
      span(class = "hand", "\U0001F44B"), "Want a custom data app like this for your project?")),
    p(style = "margin-top:12px",
      HTML("Built by <strong>Desert Data Labs</strong> · Tucson, AZ · feedback or custom dashboards → "),
      tags$a(href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Plant%20Diversity%20Explorer", "desertdatalabs@gmail.com")),
    p(style = "font-size:12px;opacity:.85",
      "Data: NEON Plant Presence & Percent Cover (DP1.10058.001). Not affiliated with NEON, Battelle, or the NSF. An educational data-exploration tool."))
)
